name: timeliner_flutter
description: "Simple utility for rendering CSV files as timelines "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  csv: ^6.0.0
  json_annotation: ^4.9.0
  file_selector: ^1.0.4
  signals: ^6.2.0
  screenshot: ^3.0.0
  editable: "^2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1

flutter:
  uses-material-design: true
